name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow will run on pushes to the main branch, including merges from pull requests.
  workflow_run:
    workflows: ["Automated AI News Research", "Automated News Research", "Automated New Zealand News Research", "Automated Philippines News Research"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # This should match the distDir in next.config.mjs
          publish_branch: gh-pages
          cname: theneworacle.github.io # Add this if you are using a custom domain
