name: Automated News Research

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  research-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          pip install langchain-community azure-identity openai>=1.0.0 requests beautifulsoup4 PyYAML duckduckgo-search google-adk google-generativeai
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run news research script
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
        run: |
          # This script needs to be created/adapted
          # It should read agents.json, perform news research, check for duplicates in posts/,
          # generate markdown, and save it to posts/
          python scripts/research_news.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: automated-news-research-${{ github.run_id }}
          title: 'Automated News Research: New Post'
          body: |
            This PR contains a new news research post generated by the automated workflow.
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
